"use client"
import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { ArrowUpRight, Loader2, Search } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { getTransactions, formatDate, formatNaira, Transaction, customerMessage } from "@/lib/teksum-api"

export function TransactionsPageClient(){
 const [items,setItems]=useState<Transaction[]>([]);const [query,setQuery]=useState("");const [status,setStatus]=useState("all");const [category,setCategory]=useState("all");const [loading,setLoading]=useState(true);const [error,setError]=useState("")
 useEffect(()=>{getTransactions("limit=100").then(r=>setItems(r.items)).catch(e=>setError(customerMessage(e,"We could not load your transactions right now. Please try again shortly."))).finally(()=>setLoading(false))},[])
 const filtered=useMemo(()=>items.filter(t=>{const q=query.toLowerCase();return(!q||t.reference.toLowerCase().includes(q)||t.category.toLowerCase().includes(q)||(t.providerName||"").toLowerCase().includes(q))&&(status==="all"||t.status===status)&&(category==="all"||t.category===category)}),[items,query,status,category])
 return <div className="flex min-w-0 flex-1 flex-col gap-6 p-4 pt-2 lg:p-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-500">Activity</p><h1 className="mt-1 text-3xl font-black tracking-tight">Transactions</h1><p className="mt-1 text-sm text-muted-foreground">Your live TEKSUM wallet and service transaction history.</p></div><Card className="rounded-2xl"><CardHeader className="flex flex-col gap-3 lg:flex-row"><CardTitle className="flex-1 text-base">Transaction history</CardTitle><div className="flex flex-wrap gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="w-full sm:w-64 pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reference or service"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="h-9 rounded-lg border bg-background px-3 text-sm"><option value="all">All status</option><option>SUCCESS</option><option>PENDING</option><option>FAILED</option><option>REVERSED</option></select><select value={category} onChange={e=>setCategory(e.target.value)} className="h-9 rounded-lg border bg-background px-3 text-sm"><option value="all">All services</option><option>DATA</option><option>AIRTIME</option><option>EDUCATION_PIN</option><option>CABLE</option><option>ELECTRICITY</option><option>WALLET_FUNDING</option></select></div></CardHeader><CardContent>{loading?<div className="flex items-center justify-center gap-2 py-16 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin"/>Loading transactions…</div>:error?<p className="py-10 text-center text-sm text-destructive">{error}</p>:filtered.length===0?<p className="py-10 text-center text-sm text-muted-foreground">No transactions match your filters.</p>:<div className="overflow-x-auto"><div className="min-w-[760px]"><div className="grid grid-cols-[1.3fr_150px_130px_150px_80px] gap-3 border-b pb-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground"><span>Reference</span><span>Service</span><span>Amount</span><span>Date</span><span>Status</span></div>{filtered.map(t=><Link key={t.id} href={`/dashboard/transactions/${encodeURIComponent(t.reference)}`} className="grid grid-cols-[1.3fr_150px_130px_150px_80px] items-center gap-3 border-b py-4 text-sm transition hover:bg-muted/30 last:border-0"><div><p className="font-mono text-xs font-semibold">{t.reference}</p><p className="text-[11px] text-muted-foreground">{t.providerName||"TEKSUM"}</p></div><span>{t.category.replaceAll("_"," ")}</span><span className="font-bold tabular-nums">{formatNaira(t.amount)}</span><span className="text-xs text-muted-foreground">{formatDate(t.createdAt)}</span><Badge variant="secondary">{t.status}</Badge><ArrowUpRight className="size-4 text-muted-foreground"/></Link>)}</div></div>}</CardContent></Card></div>
}
