"use client"
import { useEffect, useState } from "react"
import Link from "next/link"
import { ArrowLeft, CheckCircle2, Clock3, Copy, Loader2, XCircle } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { formatDate, formatNaira, apiFetch, customerMessage } from "@/lib/teksum-api"

function Status({ status }: { status: string }) { const s=status.toUpperCase(); if(s==="SUCCESS") return <Badge className="bg-emerald-500/10 text-emerald-600"><CheckCircle2 className="mr-1 size-3"/>Success</Badge>; if(s==="PENDING") return <Badge className="bg-amber-500/10 text-amber-600"><Clock3 className="mr-1 size-3"/>Pending</Badge>; return <Badge className="bg-destructive/10 text-destructive"><XCircle className="mr-1 size-3"/>Failed</Badge> }
export default function Page({params}:{params:Promise<{id:string}>}){const [id,setId]=useState("");const [tx,setTx]=useState<any>(null);const [error,setError]=useState("");useEffect(()=>{params.then(p=>setId(p.id))},[params]);useEffect(()=>{if(!id)return;apiFetch<any>(`/transactions/${encodeURIComponent(id)}`).then(setTx).catch(e=>setError(customerMessage(e,"We couldn't load that transaction right now.")))},[id]);return <div className="teksum-dashboard-page min-w-0 w-full flex flex-1 flex-col gap-6"><Link href="/dashboard/transactions" className="inline-flex w-fit items-center text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="mr-2 size-4"/>Back to transactions</Link>{!tx&&!error&&<div className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin"/>Loading transaction…</div>}{error&&<p className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{tx&&<Card className="max-w-2xl rounded-2xl"><CardHeader><div className="flex flex-col items-start gap-2 sm:flex-row sm:items-center sm:justify-between"><CardTitle>Transaction details</CardTitle><Status status={tx.status}/></div></CardHeader><CardContent className="space-y-4"><div className="rounded-2xl bg-muted/50 p-5"><p className="text-xs text-muted-foreground">{tx.category.replaceAll("_"," ")}</p><p className="mt-1 text-3xl font-black">{formatNaira(tx.amount)}</p><p className="mt-1 text-xs text-muted-foreground">{formatDate(tx.createdAt)}</p></div>{[["Reference",tx.reference],["Service",tx.category.replaceAll("_"," ")],["Type",tx.type||"—"],["Fee",formatNaira(tx.fee)]].map(([k,v])=><div key={k} className="flex items-start justify-between gap-6 border-b py-3 last:border-0"><span className="text-sm text-muted-foreground">{k}</span><span className="max-w-[65%] break-words text-right text-sm font-medium">{v}</span></div>)}<Button variant="outline" size="sm" onClick={()=>navigator.clipboard?.writeText(tx.reference)}><Copy className="mr-2 size-3"/>Copy reference</Button>{tx.fulfillment&&<div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/[.05] p-4"><p className="font-semibold">Your digital item</p><p className="mt-1 text-xs text-muted-foreground">Keep these details private.</p><div className="mt-3 space-y-2">{Object.entries(tx.fulfillment as Record<string,unknown>).map(([key,value])=><div key={key} className="rounded-xl bg-background p-3"><p className="text-xs text-muted-foreground">{key.replace(/([A-Z])/g," $1")}</p><p className="mt-1 break-all font-mono text-sm">{Array.isArray(value)?value.join("\n"):String(value)}</p></div>)}</div></div>}</CardContent></Card>}</div>}
